import Foundation
import Yams

/// The starter rule `spacekit rules new` and the app's New Rule both write.
public enum RuleScaffold {
    /// A rule for `paths`, or for folders named `match` (next to a `sibling` file, when given). Protected rules get
    /// no action; everything else is removable.
    public static func rule(
        name: String, paths: [String] = [], match: String? = nil, sibling: String? = nil, safety: SafetyLevel = .review,
        group: String = "Custom"
    ) -> Rule {
        var rule = Rule(
            id: "custom." + Rule.slug(name), name: name, group: group, category: "personal.custom",
            description: "Describe what this is and what happens if it's removed.",
            paths: paths, safety: SafetySpec(level: safety), action: safety == .protected ? ActionSpec() : ActionSpec(remove: true))
        if let match { rule.match = PatternSpec(names: [match], sibling: sibling.map { [$0] } ?? []) }
        return rule
    }

    /// The rule as a commented YAML file. `note` is added to the header, e.g. how to load the rule.
    public static func yaml(_ rule: Rule, note: String? = nil) throws -> String {
        let header = [
            "# Schema: docs/RULES.md" + (note.map { " · " + $0 } ?? ""),
            "# granularity: whole (the folder is one item) or children (each entry inside is one)",
            "# safety.level: safe (regenerated by its tool) | review | protected (never removed)",
        ]
        return header.joined(separator: "\n") + "\n" + (try YAMLEncoder().encode(rule))
    }
}
