import Foundation

// Writes the built-in rule files as Swift source for SpaceKitCore (run by the EmbedRules build plugin).
//
//   RuleEmbedder <rules folder> <output.swift> <relative path>...
//
// The text is embedded as is: a String's `debugDescription` is a Swift string literal holding it exactly. Whether it
// parses and validates is checked by SpaceKitCore's tests, which have the rule parser. A file that can't be read fails
// the build.

let arguments = CommandLine.arguments.dropFirst()
guard arguments.count >= 2 else {
    FileHandle.standardError.write(Data("usage: RuleEmbedder <rules folder> <output.swift> <relative path>...\n".utf8))
    exit(2)
}
let root = arguments[arguments.startIndex]
let output = arguments[arguments.startIndex + 1]
let names = arguments.dropFirst(2)

var source = """
    // Generated by the EmbedRules build plugin from the repository's rules/ folder. Don't edit; edit rules/ instead.

    enum EmbeddedRuleFiles {
        static let all: [(path: String, yaml: String)] = [

    """
for name in names {
    let text: String
    do {
        text = try String(contentsOfFile: root + "/" + name, encoding: .utf8)
    } catch {
        FileHandle.standardError.write(Data("error: can't read rules/\(name): \(error.localizedDescription)\n".utf8))
        exit(1)
    }
    source += "        (path: \(name.debugDescription), yaml: \(text.debugDescription)),\n"
}
source += "    ]\n}\n"

do {
    try source.write(toFile: output, atomically: true, encoding: .utf8)
} catch {
    FileHandle.standardError.write(Data("error: can't write \(output): \(error.localizedDescription)\n".utf8))
    exit(1)
}
